### ISSUE TITLE
Consider disabling parameters set for non GET requests

### ISSUE THREAD

**Issue by BradMclain** [anomaly/prestans#86]
Will be worth examining HTTP spec and best practices before doing this.

**Comment by devraj** [comment]
- From reading it's perfectly fine by the HTTP protocol to send parameters as part of the query string
- This issue was lodged after a fringe case where the body of a POST request was empty and the query string had parameters, this caused the Xhr request to default the body type to multipart form data.
- POST nearly always have data in the body
